server:
    port: 7788
info:
    version: '@project.version@'
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:jiakao@localhost:1111/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true

spring:
  application:
    name: ANDROID-MONITOR
  redis:
    database: 0
    host: localhost
    port: 6379
    password: jiakao
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 5000
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 30000
  datasource:
    url: jdbc:mysql://localhost:3306/jiakao
    username: jiakao
    password: ADoZw4P5f5Dy2fPpJ0dB8XIoPS0hVgEPkoAX1nbPDnhkT18iU7fFGWXotUM0g8QN6VCAXmspWaFX9Hl8qUc55w==
    druid:
      initial-size: 8
      min-idle: 8
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
        slf4j:
          result-set-log-enabled: false
          statement-executable-sql-log-enable: true
          enabled: true
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${publickey}
  zipkin:
    # 用zipkin收集日志
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 收集每个请求信息.默认只收集10%即0.1
      percentage: 1
publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMaCLgcq8whCuPQicZWTsnF/anXtuuxBiSVz4i52ocLJ7XOd0w+rhY/OVyGPx4law5rUIXpj3z3GJtjPoBteKAUCAwEAAQ==

logging:
  config: classpath:logback-spring.xml
mybatis:
  config-location: classpath:mybatis/mybatis-configuration.xml
  type-aliases-package: com.hqh.android.entity
  mapper-locations: classpath:mapper/*.xml
management:
  security:
    enabled: false

jiakao:
  version: 1.0.0-RELEASE
  pky-roleID: 76
  monitor-roleID: 77
  dvrcom:
     url: http://localhost:8081/dvr_camera_server/driver.serv
     method: CaptureJPEGPicture
     picSize: 2
     picQuality: 0
  service_wsclient_context: ws-client/client
  tmri:
    # 0表示不启用,1表示开启,下同
    17C51: 0
    17C52: 0
    17C53: 0
    17C54: 0
    17C55: 0
    17C56: 0
    17C57: 0
    17C58: 0
    17CB2: 0
    17CB3: 0
